name: TgiF
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib>3.1.1
  - astropy
  - tqdm
  - pandas
  - jupyter
  - ipython
  - seaborn 
  - scikit-learn
  - pip
  - pip:
    - jax
    - jaxlib
    - emcee
    #- fbpca
